### ISSUE TITLE
Problem with unhealthy containers

### ISSUE THREAD

**Issue by wmcvetty** [UltimateSoftware/AGENT#1]
I am getting unhealthy containers when trying to run the docker-compose up -d command. 

![image](https://user-images.githubusercontent.com/5152498/53263609-87597e80-369f-11e9-8ee3-da7eef9e2985.png)

I am not sure if it is to do with using docker toolbox on windows 7 or something else, any insight?

**Comment by Chraneco** [comment]
This sometimes happens when the system does not come up fast enough due to resource constraints. Please try to increase the number of cores and RAM assigned to docker.

**Comment by wmcvetty** [comment]
upping RAM fixed that, thanks so much!
