### ISSUE TITLE
Error executing command, status code 400

### ISSUE THREAD

**Issue by williamdewitt** [UltimateSoftware/AGENT#3]
Hi,

I am getting the above error when executing this against a Drupal 7 based website.  I have boiled it down to the fact that although JQuery is installed, the $ is not available and thus breaks when trying to execute scripts that use it.

Do I rebuild the exp_test_agent with some changes to make it work, create a drupal_exp_test_agent (how would this be implemented in the architecture?) or is there another solution?

Thanks,
W

**Comment by Castyr** [comment]
It's odd that you are getting a 400. Could you post the stack trace here? The AGENT checks if jQuery is installed, which is probably returning true in your case, then it tries to use the $. In the future we plan to remove jQuery completely as a dependency, an immediate fix would obviously be to make the $ available, however we are looking into a solution to make the check and usage of jQuery more robust, which the stack trace would help with.

**Comment by williamdewitt** [comment]
I resolved this issue by installing the jquery_dollar module. But now I have a new issue...
