### ISSUE TITLE
Slack Channel?

### ISSUE THREAD

**Issue by williamdewitt** [UltimateSoftware/AGENT#5]
I don't know how else to chat to you guys...  is there a Slack channel that we can get on?

**Comment by Castyr** [comment]
We just created this, we'll have to add it to the docs https://join.slack.com/t/aitesting-workspace/shared_invite/enQtNTYyNjc5MTU2OTQ3LWU4MWNlOTVhYTczYjIzZmE4NDhiZTU2MDIwYTIyMTc0MGJhYjUwM2E0Njg3YzAwMTU3MzEyYTc1MGZjNmVhMWU

**Comment by Tapanmittal13** [comment]
@Castyr hey is this slack channel active? I am not able to access the channel
